before_script:
  - sudo apt-get update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 11
language: ruby
rvm:
  - 2.5.3
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "11"