development:
  adapter: postgresql
  database: x5_development
  username: 'y'
  password: 'yyyy'
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: x5_production
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: x5_test
  pool: 5
  timeout: 5000